### PR TITLE
A skip is basically a read to a null buffer

### LINKED ISSUE #1551: [BUG] 2.84.0-preview.4: SKCodec.Create - Value cannot be null. Parameter name: buffer
**Description**

Exception **"Value cannot be null. Parameter name: buffer"** on `SKCodec.Create` - stack:
```
SkiaSharp.SKManagedStream.OnReadManagedStream(IntPtr buffer, IntPtr size)
SkiaSharp.SKAbstractManagedStream.ReadInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
SkiaSharp.SKCodec.Create(SKStream stream, SKCodecResult& result)
```

This only happens on a few images - attached one.

**Code**

```csharp
// inStream is a filestream
using var imgStream = new SKManagedStream(inStream);
using var codec = SKCodec.Create(imgStream, out SKCodecResult result);
```

**Basic Information**

Version with issue: 2.84.0-preview.4
Last known good version: 2.84.0-preview.1
IDE: Visual Studio 2019
Platform Target Frameworks: .NETFramework 4.8

**Image File Sample**

file-22

### LINKED ISSUE #1621: [BUG] SkBitmap.Decode always fail some images, but using SKImage.FromEncodedData works
**Description**

I am trying to load images in UWP with StorageFile, but some images always fail with a weird error message. 

**Code**

```
using (var stream = await storageFile.OpenStreamForReadAsync())
{
    SKBitmap bitmap = SKBitmap.Decode(stream);
    // the rest
}
```

**Expected Behavior**

the image should be loaded

**Actual Behavior**

some pictures fail at the line of calling SKBitmap.Decode, with this error message:

```
Value cannot be null.
Parameter name: buffer
```

**Basic Information**

- Version with issue:  2.80.3-preview.24
- Last known good version:  N/A
- IDE:  VS.NET
- Platform Target Frameworks: 10.0.19041.0 - 10.0.17763.0
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:  6.2.10
  - watchOS:  
  - Windows Classic:  
- Target Devices:   x64
  
** Details ** 

The manifest permission is all opened. For those images that fail, I can call `GetThumbnailAsync` properly. 

Moreover, the stream is not null, I added the following code: 

```
                        if (stream.CanRead && stream.CanSeek)
                        {
                            stream.Seek(0, SeekOrigin.Begin);
                        }
```

these lines pass, and the `Decode` still failed. 

However, if I do this instead: 

```
SKImage img = SKImage.FromEncodedData(stream);
SKBitmap bitmap = SKBitmap.FromImage(img);
```  

Now those images can be loaded. 

but why? 

**Screenshots**

I uploaded one failed image in SO: 
https://stackoverflow.com/questions/66096184/why-does-skiasharp-fail-to-load-some-image-in-uwp-when-calling-skbitmap-decode

**Reproduction Link**

### LINKED ISSUE #1752: [BUG] SKManagedStream crash loading bmp files introduced in 2.80.3
**Description**

We use C# streams to load BMP images from disk, and hand those streams directly to SKBitmap.Decode(). 
After updating from 2.80.2 to 2.80.3 this pattern is now crashing with the exception:
System.ArgumentNullException: 'Value cannot be null. Parameter name: buffer'

I've tracked it down to loading BMPs (JPG loading with the same code works fine) and only when the load pathway goes through SKManagedStream. Any method that uses this class to load this type of file (whether I make the SKManagedStream from the C# stream and give it to the Decode() function, or hand the Decode() function the C# stream directly) crashes loading BMPs.

Here is the stack track:

```
 	SkiaSharp.dll!SkiaSharp.SKManagedStream.OnReadManagedStream(System.IntPtr buffer, System.IntPtr size)	Unknown
 	SkiaSharp.dll!SkiaSharp.SKAbstractManagedStream.ReadInternal(System.IntPtr s, void* context, void* buffer, System.IntPtr size)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	SkiaSharp.dll!SkiaSharp.SKCodec.GetPixels(SkiaSharp.SKImageInfo info, System.IntPtr pixels, int rowBytes, SkiaSharp.SKCodecOptions options)	Unknown
 	SkiaSharp.dll!SkiaSharp.SKCodec.GetPixels(SkiaSharp.SKImageInfo info, System.IntPtr pixels)	Unknown
 	SkiaSharp.dll!SkiaSharp.SKBitmap.Decode(SkiaSharp.SKCodec codec, SkiaSharp.SKImageInfo bitmapInfo)	Unknown
 	SkiaSharp.dll!SkiaSharp.SKBitmap.Decode(SkiaSharp.SKCodec codec)	Unknown
 	SkiaSharp.dll!SkiaSharp.SKBitmap.Decode(SkiaSharp.SKStream stream)	Unknown
```

Notably, if I either read the BMP into a byte array or an SDKData first the same file decodes fine (using the following code)
SKData fileSKData = SKData.Create(fileStream);
SKBitmap returnBitmap = SKBitmap.Decode(fileSKData);

**Code**

```cs
// This throws the exception System.ArgumentNullException: 'Value cannot be null. Parameter name: buffer'
using (SKManagedStream sKManagedStream = new SKManagedStream(fileStream))
{
    // This crashes before returning from Decode()
    SKBitmap returnBitmap = SKBitmap.Decode(sKManagedStream);
}
```

**Expected Behavior**

A bitmap can be loaded via a C# stream 

**Actual Behavior**

The code crashes when loading a bmp but only through SKManagedStream

**Basic Information**

- Version with issue:  2.80.3
- Last known good version:  2.80.2
- IDE:  MSVC 2019
- Platform Target Frameworks: 
  - UWP:  19041
  - Windows Classic:  Version	10.0.19043 Build 19043
- Target Devices:   Windows Desktop

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

Make sure to allow reads to a null buffer as that is how skia does skips.

**Bugs Fixed**

- Fixes #1551
- Fixes #1621
- Fixes #1752

**API Changes**

None.

**Behavioral Changes**

None.

**Required skia PR**

None.

**PR Checklist**

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of main at time of PR
- [x] Merged related skia PRs
- [x] Changes adhere to coding standard
- [x] Updated documentation

### CODE REVIEW

File: binding/Binding/SKManagedStream.cs [hunk 1]
```diff
@@ -87,20 +87,22 @@ protected override void DisposeManaged ()
...
-				throw new ArgumentNullException (nameof (buffer));
 			if ((int)size < 0)
 				throw new ArgumentOutOfRangeException (nameof (size));
 
 			if (size == IntPtr.Zero)
 				return IntPtr.Zero;
 
+			// NOTE: some skips still requires a read as some streams cannot seek
 			using var managedBuffer = Utils.RentArray<byte> ((int)size);
 			var len = stream.Read (managedBuffer.Array, 0, managedBuffer.Length);
```
Comment (mattleibow) [inline binding/Binding/SKManagedStream.cs:98]: This is not perfect, but I will fix this in a separate PR. The annoying thing is that some streams like and say they are seekable but are not or they allow seeking past the end of the stream causing other issues...
