### PR TITLE
Fix load the font which the name contains unicode text

### LINKED ISSUE #1914: [BUG] sk_fontmgr_match_family_style must input family name argument by utf8 string
**Description**

The `sk_fontmgr_match_family_style` must input the family name argument by utf8 string. But we will input the Unicode16 string to it.

https://github.com/mono/SkiaSharp/blob/fffae82cf6ec1c4a6f490ddb780709ce9211725e/binding/Binding/SkiaApi.generated.cs#L12369-L12381

It means that we can not input any non-ascii font family name string to `sk_fontmgr_match_family_style`.

Reference: https://github.com/mono/SkiaSharp/issues/401

**Code**

```csharp
var typeface2 = SKFontManager.Default.MatchFamily("Arial"); // OK, because the `Arial` is the ASCII string.

var typeface2 = SKFontManager.Default.MatchFamily("宋体"); // Fail, because the `宋体` is the Unicode string.
```

**Expected Behavior**

We can input the font family name with the Unicode string.

**Actual Behavior**

It always returns null when we input the font family name with the Unicode string.

**Basic Information**

- Version with issue:  
- Last known good version:  
- IDE:  
- Platform Target Frameworks: 
  - Android:  
  - iOS:  
  - Linux:  
  - macOS:  
  - Tizen:   
  - tvOS:  
  - UWP:   
  - watchOS:  
  - Windows Classic:  
- Target Devices:   
  - 
  - 
  
<details>
  <summary>Detailed IDE/OS information (click to expand)</summary>
  
```

PASTE ANY DETAILED VERSION INFO HERE

```
</details>

**Screenshots**

**Reproduction Link**

### PR DESCRIPTION
**Pull request by lindexi**
**Description of Change**

I change the string input argument from `string` to IntPtr. The `sk_fontmgr_match_family_style` should input the `utf8` encoding string, but we will input the Unicode16 string to it. That is why we can not load the font which the font name contains the unicode text, such as the Chinese font.

**Bugs Fixed**

- Fixes #1914

**API Changes**

None.

**Behavioral Changes**

Now, we can load the font which the font name contains unicode text, such as the Chinese font.

**Required skia PR**

None.

**PR Checklist**

- [x] Has tests (if omitted, state reason in description)
- [ ] Rebased on top of main at time of PR
- [ ] Merged related skia PRs
- [ ] Changes adhere to coding standard
- [ ] Updated documentation

### CODE REVIEW

**Comment by lindexi** [comment]
My test demo code: https://github.com/lindexi/lindexi_gd/tree/458084f829183b7a972a7d232e82291b03994ceb/SkiaSharp/RulawnaloyerKairjemhemwemlayca

File: binding/Binding/SkiaApi.generated.cs [hunk 1]
```diff
@@ -12369,42 +12369,42 @@ private partial class Delegates {
 		// sk_fontstyleset_t* sk_fontmgr_match_family(sk_fontmgr_t*, const char* familyName)
 		#if !USE_DELEGATES
 		[DllImport (SKIA, CallingConvention = CallingConvention.Cdecl)]
-		internal static extern sk_fontstyleset_t sk_fontmgr_match_family (sk_fontmgr_t param0, [MarshalAs (UnmanagedType.LPStr)] String familyName);
+		internal static extern sk_fontstyleset_t sk_fontmgr_match_family (sk_fontmgr_t param0, IntPtr familyName);
```
Comment (mattleibow) [inline binding/Binding/SkiaApi.generated.cs:12372]: Could you rather edit this json file - remove the parameters that should not be String: https://github.com/mono/SkiaSharp/blob/main/binding/libSkiaSharp.json#L423-L443

**Review by mattleibow — CHANGES_REQUESTED** [review]
Thanks for this PR and catching those unicode issues!

The SkiaApi.generated.cs is generated by the tools, so these changes will get overwritten. You should rather edit the json file and then re-run the generator: https://github.com/mono/SkiaSharp/tree/main/utils#generate

File: binding/Binding/SkiaApi.generated.cs (hunk 1 above)
Comment (lindexi) [reply binding/Binding/SkiaApi.generated.cs:12372]: @mattleibow Thank you and I edit the json file. Could you review my code?

Comment (lindexi) [reply binding/Binding/SkiaApi.generated.cs:12372]: @mattleibow  But I fail to re-run the generator.

```
dotnet run --project=utils/SkiaSharpGenerator/SkiaSharpGenerator.csproj -- generate --config binding/libSkiaSharp.json --skia externals/skia --output binding/Binding/SkiaApi.generated.cs
Starting C# API generation...
ERROR: skiasharp-tools: An error occurred: `One or more errors occurred. (Unable to load DLL 'libclang' or one of its dependencies
```

Comment (mattleibow) [reply binding/Binding/SkiaApi.generated.cs:12372]: I think you need to install the C++ and/or desktop workloads. Not really sure exactly - usually it fails and then install more things. And even with all that, I see it just failed again so I had to run it in the dev command prompt... Need to investigate the CppAst dependencies.

Comment (mattleibow) [reply binding/Binding/SkiaApi.generated.cs:12372]: I ran the generators locally and the code is the same, so nothing more to do.

**Review by mattleibow — APPROVED** [review]
Awesome! Ready to go!

**Comment by mattleibow** [comment]
I absolutely butchered the merge, so the commit is not so great. Sorry about that - had to create a special merge commit on that: https://github.com/mono/SkiaSharp/commit/6f8fc4d3f217294e0fc866dbb04fed2e6692dd72

**Comment by lindexi** [comment]
Thank you @mattleibow
