### PR TITLE
Resolve some concurrency issues

### LINKED ISSUE #1188: [BUG] macOS native crashes in gr_backendrendertarget_get_gl_framebufferinfo
**Description**
i using SkiaSharp in a Xamarin.Forms app on macOS, after following the discussion in #1144 i have updated to the latest preview .45 which unfortunately doesn't solve the issue with native crashes for me (`gr_backendrendertarget_get_gl_framebufferinfo`). I have a different issue open which is related to `SKImage` #1164 but i'm not sure if this is the same - so here is a new open issue 🤓

 I'm using an `SKGLView` to draw several shapes and images which lead to a freeze and the following native crash.

**Code**

in my case it might be related with `GRContext.GetResourceCacheUsage` 🤷‍♂️

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x107350d28 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_dump_native_crash_info
	0x1073446e5 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_handle_native_crash
	0x107661303 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : altstack_handle_and_restore.cold.1
	0x1072c1dac - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : altstack_handle_and_restore
	0x107d34465 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MonoBundle/libSkiaSharp.dylib : gr_backendrendertarget_get_gl_framebufferinfo
	0x142ab5e43 - Unknown
	0x142ab5c3b - Unknown
	0x142ab4803 - Unknown
	0x14294fec3 - Unknown
	0x142949c63 - Unknown
	0x142946c14 - Unknown
	0x142946ae8 - Unknown
	0x142944bed - Unknown
	0x142943d6b - Unknown
	0x142943f7e - Unknown
	0x10735b1ee - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_jit_runtime_invoke
	0x10748d318 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_runtime_invoke_checked
	0x107491c9e - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_runtime_invoke
	0x1072133d2 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : xamarin_invoke_trampoline
	0x10721499b - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : xamarin_arch_trampoline
	0x107215bc6 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : xamarin_x86_64_common_trampoline
	0x7fff33acfe29 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSWindow(NSGestureRecognizer_Routing) _sendEventToGestureRecognizers:requireAcceptsFirstMouse:]
	0x7fff33ad7ac2 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]
	0x7fff33a41c5c - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]
	0x7fff33a41005 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSWindow(NSEventRouting) sendEvent:]
	0x7fff33a3f37c - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication(NSEvent) sendEvent:]
	0x7fff3388b0cf - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : -[NSApplication run]
	0x7fff3385d465 - /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit : NSApplicationMain
	0x1113e8aec - Unknown
	0x1112bc2a3 - Unknown
	0x10879d8fb - Unknown
	0x10879da91 - Unknown
	0x10735b1ee - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_jit_runtime_invoke
	0x10748d318 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_runtime_invoke_checked
	0x1074947c5 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_runtime_exec_main_checked
	0x1072b7e9c - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_jit_exec
	0x1072bafd4 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : mono_main
	0x107216578 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : xamarin_main
	0x1072173e4 - /Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MacOS/Project : main
	0x7fff6dd7a7fd - /usr/lib/system/libdyld.dylib : start

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x70000a25d000 from 0x108a2edc0
Pkilling 0x70000e14f000 from 0x108a2edc0
Pkilling 0x70000a866000 from 0x108a2edc0
Pkilling 0x70000b587000 from 0x108a2edc0
Pkilling 0x70000e758000 from 0x108a2edc0
Pkilling 0x70000ae6f000 from 0x108a2edc0
Pkilling 0x70000bb90000 from 0x108a2edc0
Pkilling 0x70000ed61000 from 0x108a2edc0
Pkilling 0x70000c199000 from 0x108a2edc0
Pkilling 0x70000c7a2000 from 0x108a2edc0
Pkilling 0x70000d740000 from 0x108a2edc0
Pkilling 0x70000e352000 from 0x108a2edc0
Pkilling 0x70000aa69000 from 0x108a2edc0
Pkilling 0x70000b78a000 from 0x108a2edc0
Pkilling 0x70000e95b000 from 0x108a2edc0
Pkilling 0x70000b072000 from 0x108a2edc0
Pkilling 0x70000bd93000 from 0x108a2edc0
Pkilling 0x70000c39c000 from 0x108a2edc0
Pkilling 0x700009d51000 from 0x108a2edc0
Pkilling 0x70000c9a5000 from 0x108a2edc0
Pkilling 0x70000d943000 from 0x108a2edc0
Pkilling 0x70000df4c000 from 0x108a2edc0
Pkilling 0x70000a663000 from 0x108a2edc0
Pkilling 0x70000e555000 from 0x108a2edc0
Pkilling 0x70000ac6c000 from 0x108a2edc0
Pkilling 0x70000b98d000 from 0x108a2edc0
Pkilling 0x70000eb5e000 from 0x108a2edc0
Pkilling 0x70000b275000 from 0x108a2edc0
Pkilling 0x70000bf96000 from 0x108a2edc0
Pkilling 0x700009f54000 from 0x108a2edc0
Pkilling 0x70000cba8000 from 0x108a2edc0
Pkilling 0x70000d1b1000 from 0x108a2edc0
Could not exec mono-hang-watchdog, expected on path '/Users/Documents/Dev/Project/Project.MyProject.MacOS/bin/Debug/Project.app/Contents/MonoBundle/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x108a2edc0
Finished thread summarizer pause from 0x108a2edc0.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
socket_transport_send Cannot transition thread 0x108a2edc0 from STATE_BLOCKING with DO_BLOCKING
```
**Expected Behavior**

SKGLView should render without any problems+

**Actual Behavior**

random freezes and stuck app - only force close or `killall lldb` helps in my case

**Basic Information**

- Version with issue:  1.68.2-preview.45
- IDE:  Visual Studio for Mac 8.5 (build 3183)
- Platform Target Frameworks: 
  - macOS: 10.15.3 (19D76)

- Target Devices:   
  - MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) | 16 GB 2133 MHz LPDDR3 | 2,3 GHz Quad-Core Intel Core i5 | Intel Iris Plus Graphics 655 1536 MB

**Reproduction Link**

### PR DESCRIPTION
**Pull request by mattleibow**
**Description of Change**

Resolve some concurrency issues. In some cases the construction and/or destruction overlap and this causes invalid states. This PR improves the locking to avoid this, but still preserves the read and write level of locking.

It also includes a few other improvements, such as making sure objects that require their "parent" object to not be GC'ed add a reference to it. In most cases it is simple, such as a canvas being owned by a surface. But, in the case of a pixmap, the ownership is a little different in that they are copies, but actually require the parent object to stick around. So, the ownership is "reversed".

There is also a few other tweaks to improve general GC reliability/interop performance.

**Bugs Fixed**

- Fixes #1188
- Resolves underlying issue for #1121 #910 #1173 #1168 #1144
- Resolves the underlying issue for the need for #1180

**API Changes**

None.

**Behavioral Changes**

Less crashes due to correct object management.

**PR Checklist**

- [x] Has tests (if omitted, state reason in description)
- [x] Rebased on top of master at time of PR
- [x] Changes adhere to coding standard
- [x] Updated documentation

### CODE REVIEW

File: binding/Binding/HandleDictionary.cs [hunk 1]
```diff
@@ -0,0 +1,215 @@
...
+		private static readonly Type BoolType = typeof (bool);
+
+#if THROW_OBJECT_EXCEPTIONS
+		internal static readonly ConcurrentBag<Exception> exceptions = new ConcurrentBag<Exception> ();
+#endif
+
+		internal static readonly ConcurrentDictionary<Type, ConstructorInfo> constructors = new ConcurrentDictionary<Type, ConstructorInfo> ();
+		internal static readonly Dictionary<IntPtr, WeakReference> instances = new Dictionary<IntPtr, WeakReference> ();
+
+		internal static readonly ReaderWriterLockSlim instancesLock = new ReaderWriterLockSlim ();
```
Comment (mattleibow) [inline binding/Binding/HandleDictionary.cs]: Instead of pure locking and concurrent dictionaries, just use a reader/writer lock as that is what we actually want. And, when reading and we find that there is no handle, then we can upgrade in place.

File: binding/Binding/HandleDictionary.cs [hunk 2]
```diff
@@ -0,0 +1,215 @@
...
+using System.Collections.Generic;
+using System.Reflection;
+using System.Threading;
+
+namespace SkiaSharp
+{
+	internal static class HandleDictionary
+	{
+		private static readonly Type IntPtrType = typeof (IntPtr);
+		private static readonly Type BoolType = typeof (bool);
```
Comment (mattleibow) [inline binding/Binding/HandleDictionary.cs]: Caching on .NET Core is a major perf boost. Major as in 3x, but still in ns.

File: binding/Binding/HandleDictionary.cs [hunk 3]
```diff
@@ -0,0 +1,215 @@
...
+								$"H: {handle.ToString ("x")} Type: {instance.GetType ()}");
+#endif
+						refcnt.SafeUnRef ();
+					}
+
+					return instance;
+				}
+
+				var type = typeof (TSkiaImplementation);
+				var constructor = constructors.GetOrAdd (type, t => GetConstructor (t));
```
Comment (mattleibow) [inline binding/Binding/HandleDictionary.cs]: Anonymous delegates are cached rather than direct method references.

File: binding/Binding/SKObject.cs [hunk 4]
```diff
@@ -1,29 +1,23 @@
...
-#if THROW_OBJECT_EXCEPTIONS
-		internal static readonly ConcurrentBag<Exception> exceptions = new ConcurrentBag<Exception> ();
-#endif
+		private ConcurrentDictionary<IntPtr, SKObject> ownedObjects;
+		private ConcurrentDictionary<IntPtr, SKObject> keepAliveObjects;
 
-		internal static readonly ConcurrentDictionary<Type, ConstructorInfo> constructors;
-		internal static readonly ConcurrentDictionary<IntPtr, WeakReference> instances;
+		internal ConcurrentDictionary<IntPtr, SKObject> OwnedObjects =>
+			ownedObjects ??= new ConcurrentDictionary<IntPtr, SKObject> ();
```
Comment (mattleibow) [inline binding/Binding/SKObject.cs]: Lazy-instantiate this as it is hardly ever used. Typically for documents and some for some streams, codecs and typefaces.

File: tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj [hunk 5]
```diff
@@ -12,18 +12,13 @@
     <PackageReference Include="xunit" Version="2.4.1" />
     <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
     <PackageReference Include="XunitXml.TestLogger" Version="2.1.26" />
-    <PackageReference Include="xunit.assemblyfixture" Version="2.0.3" />
```
Comment (mattleibow) [inline tests/SkiaSharp.NetCore.Tests/SkiaSharp.NetCore.Tests.csproj]: This never worked for .NET Core anyway. Use the xUnit-approved way from the xUnit samples.

**Comment by mattleibow** [comment]
Thanks for the review!

Technically, the objects should only be referenced from a single thread at any given time. However, I will add some locking to prevent any future issues.

File: binding/Binding/SKBitmap.cs [hunk 6]
```diff
@@ -718,7 +718,10 @@ public bool PeekPixels (SKPixmap pixmap)
 			if (pixmap == null) {
 				throw new ArgumentNullException (nameof (pixmap));
 			}
-			return SkiaApi.sk_bitmap_peek_pixels (Handle, pixmap.Handle);
+			var result = SkiaApi.sk_bitmap_peek_pixels (Handle, pixmap.Handle);
+			if (result)
+				Referenced (pixmap, this);
```
Comment (mattleibow) [inline binding/Binding/SKBitmap.cs:723]: The GC sometimes likes to collect the bitmap in use by a pixmap. This case is important because the bitmap OWNS the pixmap, and the reference is not counted. So a disposal destroys the pixmap.

File: binding/Binding/SKData.cs [hunk 7]
```diff
@@ -251,6 +251,7 @@ public void SaveTo (Stream target)
 			} finally {
 				ArrayPool<byte>.Shared.Return (buffer);
 			}
+			GC.KeepAlive (this);
```
Comment (mattleibow) [inline binding/Binding/SKData.cs:254]: Just prevent the GC from going to town, because we are not actually using the object, but a value from one of the properties.

File: binding/Binding/SKObject.cs [hunk 8]
```diff
@@ -1,29 +1,41 @@
...
 using System.Threading;
 
 namespace SkiaSharp
 {
 	public abstract class SKObject : SKNativeObject
 	{
-#if THROW_OBJECT_EXCEPTIONS
-		internal static readonly ConcurrentBag<Exception> exceptions = new ConcurrentBag<Exception> ();
-#endif
+		private readonly object locker = new object ();
```
Comment (mattleibow) [inline binding/Binding/SKObject.cs:10]: A single locker as this doesn't need to be too complicated.

**Comment by mattleibow** [comment]
I think this is it. Fixed some other bugs. Concurrency due to construction and destruction, but also when the GC starts to collect things too soon.

**Comment by mattleibow** [comment]
I have pushed what I think is now a good version to the preview feed: https://aka.ms/skiasharp-eap/index.json
Check out the PR version: **1.68.2-pr.1200.20**

**Comment by Gillibald** [comment]
Will have a look shortly 👍

**Comment by mattleibow** [comment]
@Gillibald have you been able to have a look and see if things are better? I am thinking of just merging and pushing to nuget.org so that the mapsui folks can check. But, I just want to make sure that I get your opinion/hands on the pie here.

**Comment by Gillibald** [comment]
Did not have time today. Could do tomorrow morning. In a few hours 😀. My current test creates and disposes millions of SKObjects. So minimal improvements should come out clearly. Mostly text related objects.

**Comment by mattleibow** [comment]
Ah, millions? Have you noticed any random crashes or weird behavior at all 😄 

The issues that mostly come up is with concurrent execution because objects were being created with the same handle as an object being destroyed. As a result, the managed side got all mixed up as it was busy nuking things and then it is added back, or worse the reverse. Most of the cases coming now are when people use the GL views because that is usually for high frequency updates and often on separate threads. 

So this would be interesting to see if you were seeing weird things, or even having to do some weird things to prevent weird things 😄

**Comment by Gillibald** [comment]
Luckily I only have to deal with single threaded processing. I might want to put text processing on a dedicated thread in the near future.

**Comment by Gillibald** [comment]
The preview runs just fine. After this is merged I will work on the changes to SKObject.GetObject
Using cached delegates instead of reflection should improve things a bit.

Do we really need to keep track of all SKObject instances? Ideally, we could just turn off caching.

**Comment by mattleibow** [comment]
We have to track them because if I call `SKSurface.Canvas` twice, I need to find it again. I can't really cache it directly, because some operations might destroy the canvas and then the object is destroyed in native code, but we still got a valid object in managed world. Sometimes we don't even know when it will happen, as it may be a result of another operation. It is easy from a developer's perspective because certain operations may do things, but to get it right it is going to be more difficult.

I know @kekekeks was asking for a pointer-only API: #876 

But, this is not to say we can't actually have a look at certain APIs and see if we can just store things in a field. For example, a surface will always have the same canvas, so no need to even go through the interop. But this is not true for `SKBitmap.PeekPixels` because a copy is made of the pixmap, and you can always change the underlying pixel pointer at time - and this will not reflect in the copied pixmap.

Overall, the slowest point of this library is the lookup. And this is made harder because some objects are reference counted, others are not. And then, some are reference counted, but not used like one. The API is not quite perfect.

**Comment by mattleibow** [comment]
Thanks for having a look. Merging this now so I can get a preview out.
